baseURL = "https://91haba.github.io/"
languageCode = "en-us"
title = "Habalopment"
theme = "crab"

[params]
description = "develophgraphy"
copyright = "91haba"

[[menu.main]]
weight = 1
name = "Home"
url = "/"